### ISSUE TITLE
What modification should I make to port to ATmega16?

### ISSUE THREAD

**Issue by hayschan** [MajicDesigns/MD_PWM#3]
I use Microchip Studio (former Atmel Studio) for writing C code for ATmega16.

> The library should work on other Arduino boards (eg, MEGA) with slight modifications

What modification should I make to port to ATmega16?

**Comment by hayschan** [comment]
Besides, do I need to port Arduino functions to AVR C?
https://github.com/MajicDesigns/MD_PWM/blob/fb43b3896401424152cf08273475dc52711312c5/src/MD_PWM.h#L133

**Comment by MajicDesigns** [comment]
At a minimum you should check that the timer routines (in 'assembler') are compatible with the ATMega16. I expect that the way the timers work will be similar but probably not identical.

MD_PWM is written in C++ (it is a class) so if you want to use a pure C compiler it will require extensive rewrite. As for the equivalence for the Arduino.h file, there are probably others (do a search) that have come up with a solution to this already as there is a lot of Arduino code around.

I would be interested to know how you go so that we can add this processor type into the library if you find it works.
